[build]
  command = "bun run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NITRO_PRESET = "netlify"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    Referrer-Policy = "no-referrer"
