/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedYoutubeTestRouteImport } from './routes/_authenticated/youtube-test'
import { Route as AuthenticatedWatchlistRouteImport } from './routes/_authenticated/watchlist'
import { Route as AuthenticatedTvRouteImport } from './routes/_authenticated/tv'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedMoviesRouteImport } from './routes/_authenticated/movies'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedYoutubeIndexRouteImport } from './routes/_authenticated/youtube.index'
import { Route as AuthenticatedPartyIndexRouteImport } from './routes/_authenticated/party.index'
import { Route as AuthenticatedAnimeIndexRouteImport } from './routes/_authenticated/anime.index'
import { Route as AuthenticatedYoutubeIdRouteImport } from './routes/_authenticated/youtube.$id'
import { Route as AuthenticatedPartyCodeRouteImport } from './routes/_authenticated/party.$code'
import { Route as AuthenticatedBrowseProviderRouteImport } from './routes/_authenticated/browse.$provider'
import { Route as AuthenticatedAnimeIdRouteImport } from './routes/_authenticated/anime.$id'
import { Route as AuthenticatedWatchTypeIdRouteImport } from './routes/_authenticated/watch.$type.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedYoutubeTestRoute =
  AuthenticatedYoutubeTestRouteImport.update({
    id: '/youtube-test',
    path: '/youtube-test',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWatchlistRoute = AuthenticatedWatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTvRoute = AuthenticatedTvRouteImport.update({
  id: '/tv',
  path: '/tv',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoviesRoute = AuthenticatedMoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYoutubeIndexRoute =
  AuthenticatedYoutubeIndexRouteImport.update({
    id: '/youtube/',
    path: '/youtube/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPartyIndexRoute = AuthenticatedPartyIndexRouteImport.update({
  id: '/party/',
  path: '/party/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnimeIndexRoute = AuthenticatedAnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYoutubeIdRoute = AuthenticatedYoutubeIdRouteImport.update({
  id: '/youtube/$id',
  path: '/youtube/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartyCodeRoute = AuthenticatedPartyCodeRouteImport.update({
  id: '/party/$code',
  path: '/party/$code',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrowseProviderRoute =
  AuthenticatedBrowseProviderRouteImport.update({
    id: '/browse/$provider',
    path: '/browse/$provider',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnimeIdRoute = AuthenticatedAnimeIdRouteImport.update({
  id: '/anime/$id',
  path: '/anime/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWatchTypeIdRoute =
  AuthenticatedWatchTypeIdRouteImport.update({
    id: '/watch/$type/$id',
    path: '/watch/$type/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/movies': typeof AuthenticatedMoviesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tv': typeof AuthenticatedTvRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/youtube-test': typeof AuthenticatedYoutubeTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/anime/$id': typeof AuthenticatedAnimeIdRoute
  '/browse/$provider': typeof AuthenticatedBrowseProviderRoute
  '/party/$code': typeof AuthenticatedPartyCodeRoute
  '/youtube/$id': typeof AuthenticatedYoutubeIdRoute
  '/anime/': typeof AuthenticatedAnimeIndexRoute
  '/party/': typeof AuthenticatedPartyIndexRoute
  '/youtube/': typeof AuthenticatedYoutubeIndexRoute
  '/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/history': typeof AuthenticatedHistoryRoute
  '/movies': typeof AuthenticatedMoviesRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tv': typeof AuthenticatedTvRoute
  '/watchlist': typeof AuthenticatedWatchlistRoute
  '/youtube-test': typeof AuthenticatedYoutubeTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/anime/$id': typeof AuthenticatedAnimeIdRoute
  '/browse/$provider': typeof AuthenticatedBrowseProviderRoute
  '/party/$code': typeof AuthenticatedPartyCodeRoute
  '/youtube/$id': typeof AuthenticatedYoutubeIdRoute
  '/anime': typeof AuthenticatedAnimeIndexRoute
  '/party': typeof AuthenticatedPartyIndexRoute
  '/youtube': typeof AuthenticatedYoutubeIndexRoute
  '/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/movies': typeof AuthenticatedMoviesRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tv': typeof AuthenticatedTvRoute
  '/_authenticated/watchlist': typeof AuthenticatedWatchlistRoute
  '/_authenticated/youtube-test': typeof AuthenticatedYoutubeTestRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/anime/$id': typeof AuthenticatedAnimeIdRoute
  '/_authenticated/browse/$provider': typeof AuthenticatedBrowseProviderRoute
  '/_authenticated/party/$code': typeof AuthenticatedPartyCodeRoute
  '/_authenticated/youtube/$id': typeof AuthenticatedYoutubeIdRoute
  '/_authenticated/anime/': typeof AuthenticatedAnimeIndexRoute
  '/_authenticated/party/': typeof AuthenticatedPartyIndexRoute
  '/_authenticated/youtube/': typeof AuthenticatedYoutubeIndexRoute
  '/_authenticated/watch/$type/$id': typeof AuthenticatedWatchTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/history'
    | '/movies'
    | '/search'
    | '/settings'
    | '/tv'
    | '/watchlist'
    | '/youtube-test'
    | '/auth/callback'
    | '/anime/$id'
    | '/browse/$provider'
    | '/party/$code'
    | '/youtube/$id'
    | '/anime/'
    | '/party/'
    | '/youtube/'
    | '/watch/$type/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/history'
    | '/movies'
    | '/search'
    | '/settings'
    | '/tv'
    | '/watchlist'
    | '/youtube-test'
    | '/auth/callback'
    | '/'
    | '/anime/$id'
    | '/browse/$provider'
    | '/party/$code'
    | '/youtube/$id'
    | '/anime'
    | '/party'
    | '/youtube'
    | '/watch/$type/$id'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/_authenticated/history'
    | '/_authenticated/movies'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/tv'
    | '/_authenticated/watchlist'
    | '/_authenticated/youtube-test'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/anime/$id'
    | '/_authenticated/browse/$provider'
    | '/_authenticated/party/$code'
    | '/_authenticated/youtube/$id'
    | '/_authenticated/anime/'
    | '/_authenticated/party/'
    | '/_authenticated/youtube/'
    | '/_authenticated/watch/$type/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/youtube-test': {
      id: '/_authenticated/youtube-test'
      path: '/youtube-test'
      fullPath: '/youtube-test'
      preLoaderRoute: typeof AuthenticatedYoutubeTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watchlist': {
      id: '/_authenticated/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof AuthenticatedWatchlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tv': {
      id: '/_authenticated/tv'
      path: '/tv'
      fullPath: '/tv'
      preLoaderRoute: typeof AuthenticatedTvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movies': {
      id: '/_authenticated/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof AuthenticatedMoviesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/youtube/': {
      id: '/_authenticated/youtube/'
      path: '/youtube'
      fullPath: '/youtube/'
      preLoaderRoute: typeof AuthenticatedYoutubeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party/': {
      id: '/_authenticated/party/'
      path: '/party'
      fullPath: '/party/'
      preLoaderRoute: typeof AuthenticatedPartyIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anime/': {
      id: '/_authenticated/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AuthenticatedAnimeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/youtube/$id': {
      id: '/_authenticated/youtube/$id'
      path: '/youtube/$id'
      fullPath: '/youtube/$id'
      preLoaderRoute: typeof AuthenticatedYoutubeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/party/$code': {
      id: '/_authenticated/party/$code'
      path: '/party/$code'
      fullPath: '/party/$code'
      preLoaderRoute: typeof AuthenticatedPartyCodeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/browse/$provider': {
      id: '/_authenticated/browse/$provider'
      path: '/browse/$provider'
      fullPath: '/browse/$provider'
      preLoaderRoute: typeof AuthenticatedBrowseProviderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anime/$id': {
      id: '/_authenticated/anime/$id'
      path: '/anime/$id'
      fullPath: '/anime/$id'
      preLoaderRoute: typeof AuthenticatedAnimeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/watch/$type/$id': {
      id: '/_authenticated/watch/$type/$id'
      path: '/watch/$type/$id'
      fullPath: '/watch/$type/$id'
      preLoaderRoute: typeof AuthenticatedWatchTypeIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMoviesRoute: typeof AuthenticatedMoviesRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTvRoute: typeof AuthenticatedTvRoute
  AuthenticatedWatchlistRoute: typeof AuthenticatedWatchlistRoute
  AuthenticatedYoutubeTestRoute: typeof AuthenticatedYoutubeTestRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnimeIdRoute: typeof AuthenticatedAnimeIdRoute
  AuthenticatedBrowseProviderRoute: typeof AuthenticatedBrowseProviderRoute
  AuthenticatedPartyCodeRoute: typeof AuthenticatedPartyCodeRoute
  AuthenticatedYoutubeIdRoute: typeof AuthenticatedYoutubeIdRoute
  AuthenticatedAnimeIndexRoute: typeof AuthenticatedAnimeIndexRoute
  AuthenticatedPartyIndexRoute: typeof AuthenticatedPartyIndexRoute
  AuthenticatedYoutubeIndexRoute: typeof AuthenticatedYoutubeIndexRoute
  AuthenticatedWatchTypeIdRoute: typeof AuthenticatedWatchTypeIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMoviesRoute: AuthenticatedMoviesRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTvRoute: AuthenticatedTvRoute,
  AuthenticatedWatchlistRoute: AuthenticatedWatchlistRoute,
  AuthenticatedYoutubeTestRoute: AuthenticatedYoutubeTestRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnimeIdRoute: AuthenticatedAnimeIdRoute,
  AuthenticatedBrowseProviderRoute: AuthenticatedBrowseProviderRoute,
  AuthenticatedPartyCodeRoute: AuthenticatedPartyCodeRoute,
  AuthenticatedYoutubeIdRoute: AuthenticatedYoutubeIdRoute,
  AuthenticatedAnimeIndexRoute: AuthenticatedAnimeIndexRoute,
  AuthenticatedPartyIndexRoute: AuthenticatedPartyIndexRoute,
  AuthenticatedYoutubeIndexRoute: AuthenticatedYoutubeIndexRoute,
  AuthenticatedWatchTypeIdRoute: AuthenticatedWatchTypeIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
